#!/usr/bin/env python3
"""Python conformance runner.

Loads every ``conformance-vectors/cases/*.json`` and asserts the Python SDK's
``canonicalize`` produces the exact ``canonical`` string and SHA-256 the
vector file recorded (generated by the TS reference runner).
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PY_SRC = REPO_ROOT / "python" / "src"
sys.path.insert(0, str(PY_SRC))

from auditlayer.schema.jcs import canonicalize  # noqa: E402

CASES_DIR = REPO_ROOT / "conformance-vectors" / "cases"


def main() -> int:
    files = sorted(p for p in CASES_DIR.glob("*.json"))
    failed = 0
    passed = 0
    for path in files:
        vector = json.loads(path.read_text(encoding="utf-8"))
        name = vector["name"]
        if "canonical" not in vector or "sha256" not in vector:
            sys.stderr.write(f"{name}: missing canonical/sha256; run TS generator first.\n")
            failed += 1
            continue
        canonical = canonicalize(vector["input"])
        sha256 = hashlib.sha256(canonical.encode("utf-8")).hexdigest()
        if canonical != vector["canonical"] or sha256 != vector["sha256"]:
            failed += 1
            sys.stderr.write(
                f"FAIL {name}\n"
                f"  expected canonical: {vector['canonical']!r}\n"
                f"  got      canonical: {canonical!r}\n"
                f"  expected sha256:    {vector['sha256']}\n"
                f"  got      sha256:    {sha256}\n",
            )
        else:
            passed += 1
    if failed == 0:
        print(f"Python conformance: {passed} passed.")
        return 0
    sys.stderr.write(f"Python conformance: {failed} failed, {passed} passed.\n")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
